### ISSUE TITLE
14th July peer-to-peer code review

### ISSUE THREAD

**Issue by Zilola-Nazarova** [GhostEsso/toDoList#4]
## Highlights 🥇 

- all the required functionalities (add, delete,  clear all completed) work;
- the styling is very close to the given minimalist example;
- data is preserved in the local storage;

## Improvement suggestions ♻️ 

- try working on the styling to have consistent paddings from the main container border;

## Additional suggestions (not required) 🌟 

- you could consider adding an event listener to the input so that the user is able to add tasks by pressing the 'Enter' key;

_If you have any questions regarding our suggestions feel free to leave comments here_

**Comment by GhostEsso** [comment]
@Zilola-Nazarova Thank you for additional  suggestions :pray:

**Comment by GhostEsso** [comment]
@Zilola-Nazarova Hi **Zilola** I have written a function to add a task when the Enter key is pressed, but the problem is that there are no changes in the application when I launch a live server. However, when I created a new folder with only the HTML, CSS, and JS files, it works fine. Do you know what could be causing this issue?

**Comment by Zilola-Nazarova** [comment]
Hi @GhostEsso 
I downloaded ZIP version of your project. Opened it in VSCode. Then I run in command line then "npm start" and everything works with "Enter" key. I think your project is fine. Maybe you could try to download it to the different folder?

https://github.com/GhostEsso/toDoList/assets/61951420/dbedfaa8-9633-4276-8ffb-d8bfd9436d0a

PS: I also had to run "npm install" (to install all node_modules) before running "npm start".

**Comment by Zilola-Nazarova** [comment]
Hi @GhostEsso
I downloaded ZIP version of your project. Opened it in VSCode. Then I ran in command line "npm start" and everything works with "Enter" key. I think your project is fine. Maybe you could try to download it to the different folder?
PS: I also had to run "npm install" because our folders are downloaded from GitHub without node_modules and I install them by this command.

**Comment by GhostEsso** [comment]
@Zilola-Nazarova Thanks a lot 🙏🏽... I'm going to try it and see...

**Comment by Zilola-Nazarova** [comment]
I also tried to play around the features.js file changing "Enter" to "Shift". I also played around style.css. The server works as expected and the application updates everytime I save the file. I wasn't able to find any issues.

https://github.com/GhostEsso/toDoList/assets/61951420/c4f7cd64-b2a0-4f12-867b-2d675eac67c3

**Comment by Zilola-Nazarova** [comment]
I did the same thing but this time I cloned your project with "git clone git@github.com:GhostEsso/toDoList.git" (Honestly, I don't know why I used "Download ZIP" approach before 😄 )
And as before, no issues found. Everything works.

**Comment by GhostEsso** [comment]
@Zilola-Nazarova Thanks for your feedback 🙏🏽🙏🏽🙏🏽

**Comment by GhostEsso** [comment]
@Zilola-Nazarova I tested, it actually works. You were able to remind me of a crucial thing, I forgot to launch npm start, I launched the project with the live server.

**Comment by Zilola-Nazarova** [comment]
@GhostEsso  yes, it was mentioned that if the project is set up with webpack, VScode Live Server doesn't work smoothly, so it's better to run "npm start"

**Comment by GhostEsso** [comment]
@Zilola-Nazarova one last concern, when I go to the live demo, there are no changes made to the application... i.e. the deployed application has not been affected by the local changes

**Comment by Zilola-Nazarova** [comment]
@GhostEsso this is a very good question. When you deploy your project running "npm deploy", the branch "gh-pages" is updated. But this branch contains only files from your ./dist folder. This folder may contain an old version of your project. In order to update the files in ./dist folder try running "npm run build".

**Comment by GhostEsso** [comment]
@Zilola-Nazarova You're genius! Thanks for all... It's working :smiley:
